apiVersion: builtin
kind: PatchTransformer
metadata:
  name: changeEnv
target:
  group: apps
  version: v1
  kind: Deployment
  name: nginx-deployment
patch: |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: nginx-deployment
  spec:
    template:
      spec:
        containers:
        - name: nginx
          env:
          - name: add-env
            value: env